packages:
  - apps/*
  - libraries/*

overrides:
  next: 16.2.7
  react: 19.2.7
  react-dom: 19.2.7
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6

onlyBuiltDependencies:
  - bcrypt
  - '@sentry-internal/node-cpu-profiler'
