export interface ProviderCapability {
  analytics: boolean;
  comments: boolean;
  firstComment: boolean;
  poll: boolean;
  video: boolean;
  carousel: boolean;
  altText: boolean;
  maxMedia: number;
  linkPreview: boolean;
  refreshToken: boolean;
  watchlist: boolean;
  // Whether the provider's markdown/html editor supports rich-text block/link
  // constructs (links, bullets, headings). Optional: absent means supported —
  // only set `false` for a provider whose editor lacks them (e.g. telegram's
  // markdown flavour). Composer editor reads this via `richText ?? true`.
  richText?: boolean;
}

export const PROVIDER_CAPABILITIES: Record<string, ProviderCapability> = {
  'x': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: true,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 4,
    linkPreview: true,
    refreshToken: true,
    watchlist: true,
  },
  'linkedin': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: true,
    video: true,
    carousel: true,
    altText: false,
    maxMedia: 20,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'linkedin-page': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: true,
    video: true,
    carousel: true,
    altText: false,
    maxMedia: 20,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'reddit': {
    // `analytics: true` here means "the provider feeds the analytics surface"
    // — post-level only (score / upvote ratio / comments via postAnalytics());
    // Reddit exposes no per-account channel analytics() (see the adapter's own
    // comment). This single boolean can't express post-vs-channel; splitting it
    // into separate post/channel flags is a tracked follow-up, not this branch.
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 1,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'instagram': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: true,
    carousel: true,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: true,
    watchlist: true,
  },
  'instagram-standalone': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: true,
    carousel: true,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: true,
    watchlist: true,
  },
  'facebook': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'threads': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: true,
    carousel: true,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'youtube': {
    analytics: true,
    comments: true,
    firstComment: false,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 1,
    linkPreview: false,
    refreshToken: true,
    watchlist: true,
  },
  'gmb': {
    analytics: true,
    comments: false,
    firstComment: false,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 1,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'tiktok': {
    analytics: true,
    comments: true,
    firstComment: false,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 1,
    linkPreview: false,
    refreshToken: true,
    watchlist: true,
  },
  'pinterest': {
    analytics: true,
    comments: false,
    firstComment: false,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 5,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'dribbble': {
    analytics: true,
    comments: false,
    firstComment: false,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 1,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'discord': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'slack': {
    analytics: false,
    comments: true,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: true,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'kick': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'twitch': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'mastodon': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: true,
    carousel: false,
    altText: true,
    maxMedia: 4,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'bluesky': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: true,
    carousel: false,
    altText: true,
    maxMedia: 4,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'lemmy': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 1,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'wrapcast': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 4,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'telegram': {
    analytics: true,
    comments: true,
    firstComment: true,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
    // Telegram's markdown flavour has no link/bullet/heading toolbar support.
    richText: false,
  },
  'nostr': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'vk': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'medium': {
    analytics: false,
    comments: true,
    firstComment: false,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'devto': {
    analytics: false,
    comments: true,
    firstComment: false,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'hashnode': {
    analytics: false,
    comments: true,
    firstComment: false,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'wordpress': {
    analytics: false,
    comments: true,
    firstComment: false,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'listmonk': {
    analytics: false,
    comments: false,
    firstComment: false,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'moltbook': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'whop': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 0,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'skool': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'mewe': {
    analytics: false,
    comments: false,
    firstComment: false,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'tumblr': {
    analytics: false,
    comments: false,
    firstComment: false,
    poll: false,
    video: true,
    carousel: false,
    altText: true,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: true,
    watchlist: false,
  },
  'pixelfed': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: false,
    carousel: false,
    altText: true,
    maxMedia: 10,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
  'peertube': {
    analytics: false,
    comments: false,
    firstComment: true,
    poll: false,
    video: true,
    carousel: false,
    altText: false,
    maxMedia: 1,
    linkPreview: false,
    refreshToken: false,
    watchlist: false,
  },
};
