import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Postmill Docs',
  description: 'Schedule social & chat posts across 36 channels',
  markdown: {
    languageAlias: {
      env: 'ini',
      caddyfile: 'nginx',
    },
  },
  themeConfig: {
    nav: [
      { text: 'User Guide', link: '/user-guide/' },
      { text: 'Developer Docs', link: '/developer-docs/' },
      { text: 'Operations Guide', link: '/operations-guide/' },
    ],
    sidebar: {
      '/user-guide/': [
        {
          text: 'User Guide',
          items: [
            { text: 'Introduction', link: '/user-guide/' },
            { text: 'Getting Started', link: '/user-guide/getting-started' },
            { text: 'First-Run Setup', link: '/user-guide/first-run-setup' },
            { text: 'Dashboard', link: '/user-guide/dashboard' },
            { text: 'Calendar & Posts', link: '/user-guide/calendar' },
            { text: 'Composer', link: '/user-guide/composer' },
            { text: 'Bulk Import', link: '/user-guide/bulk-import' },
            { text: 'Analytics', link: '/user-guide/analytics' },
            { text: 'Watchlist', link: '/user-guide/watchlist' },
            { text: 'Social Comments', link: '/user-guide/social-comments' },
            { text: 'Campaigns', link: '/user-guide/campaigns' },
            { text: 'Media Library', link: '/user-guide/media-library' },
          ],
        },
        {
          text: 'Media Studios',
          items: [
            { text: 'Overview', link: '/user-guide/media/' },
            {
              text: 'Platform',
              collapsed: true,
              items: [
                { text: 'AI Designer', link: '/user-guide/media/ai-designer' },
                { text: 'Designer', link: '/user-guide/media/designer' },
              ],
            },
            {
              text: 'Providers',
              collapsed: true,
              items: [
                { text: 'Amazon Bedrock', link: '/user-guide/media/bedrock' },
                { text: 'Azure OpenAI', link: '/user-guide/media/azure' },
                { text: 'Black Forest Labs', link: '/user-guide/media/black-forest-labs' },
                { text: 'D-ID', link: '/user-guide/media/did' },
                { text: 'Deepgram', link: '/user-guide/media/deepgram' },
                { text: 'DeepInfra', link: '/user-guide/media/deepinfra' },
                { text: 'ElevenLabs', link: '/user-guide/media/elevenlabs' },
                { text: 'Fireworks AI', link: '/user-guide/media/fireworks' },
                { text: 'Genviral', link: '/user-guide/media/genviral' },
                { text: 'Google AI Studio', link: '/user-guide/media/google-ai' },
                { text: 'Google Vertex', link: '/user-guide/media/vertex' },
                { text: 'Groq', link: '/user-guide/media/groq' },
                { text: 'Hedra', link: '/user-guide/media/hedra' },
                { text: 'HeyGen', link: '/user-guide/media/heygen' },
                { text: 'Higgsfield', link: '/user-guide/media/higgsfield' },
                { text: 'Ideogram', link: '/user-guide/media/ideogram' },
                { text: 'Kling', link: '/user-guide/media/kling' },
                { text: 'Leonardo.ai', link: '/user-guide/media/leonardo' },
                { text: 'LTX Studio', link: '/user-guide/media/ltx' },
                { text: 'Luma', link: '/user-guide/media/luma' },
                { text: 'MiniMax', link: '/user-guide/media/minimax' },
                { text: 'OpenAI', link: '/user-guide/media/openai' },
                { text: 'OpenRouter', link: '/user-guide/media/openrouter' },
                { text: 'Pika', link: '/user-guide/media/pika' },
                { text: 'Qwen', link: '/user-guide/media/qwen' },
                { text: 'Recraft', link: '/user-guide/media/recraft' },
                { text: 'Reel.Farm', link: '/user-guide/media/reelfarm' },
                { text: 'Replicate', link: '/user-guide/media/replicate' },
                { text: 'Runway', link: '/user-guide/media/runway' },
                { text: 'SiliconFlow', link: '/user-guide/media/siliconflow' },
                { text: 'Sora', link: '/user-guide/media/sora' },
                { text: 'Stability AI', link: '/user-guide/media/stability-ai' },
                { text: 'Suno', link: '/user-guide/media/suno' },
                { text: 'Tavus', link: '/user-guide/media/tavus' },
                { text: 'Together AI', link: '/user-guide/media/togetherai' },
                { text: 'Vercel AI', link: '/user-guide/media/gateway' },
                { text: 'Wan', link: '/user-guide/media/wan' },
                { text: 'xAI Grok', link: '/user-guide/media/xai' },
              ],
            },
            {
              text: 'Content Pack',
              collapsed: true,
              items: [
                { text: 'Icons', link: '/user-guide/media/stock-icons' },
                { text: 'Stickers', link: '/user-guide/media/stock-stickers' },
                { text: 'Stock Audio', link: '/user-guide/media/stock-audio' },
                { text: 'Stock Photos', link: '/user-guide/media/stock-photos' },
                { text: 'Stock Videos', link: '/user-guide/media/stock-videos' },
                { text: 'Vectors', link: '/user-guide/media/stock-vectors' },
              ],
            },
          ],
        },
        {
          text: 'More',
          items: [
            { text: 'AI Tools', link: '/user-guide/ai-tools' },
            { text: 'AI Agent', link: '/user-guide/agent' },
            { text: 'Notifications', link: '/user-guide/notifications' },
            { text: 'Settings', link: '/user-guide/settings' },
            { text: 'Team & Roles', link: '/user-guide/team-and-roles' },
            { text: 'Sessions & Devices', link: '/user-guide/sessions' },
            { text: 'Subscription & Billing', link: '/user-guide/subscription-and-billing' },
            { text: 'Supported Channels', link: '/user-guide/supported-channels' },
          ],
        },
      ],
      '/developer-docs/': [
        {
          text: 'Developer Docs',
          items: [
            { text: 'Introduction', link: '/developer-docs/' },
            { text: 'Architecture', link: '/developer-docs/architecture' },
            { text: 'Data Model', link: '/developer-docs/data-model' },
            { text: 'Database', link: '/developer-docs/database' },
            { text: 'Backend Conventions', link: '/developer-docs/backend-conventions' },
            { text: 'Frontend Conventions', link: '/developer-docs/frontend-conventions' },
            { text: 'Provider Framework', link: '/developer-docs/provider-framework' },
            { text: 'Integrations', link: '/developer-docs/integrations' },
          ],
        },
        {
          text: 'APIs',
          items: [
            { text: 'Public API v1', link: '/developer-docs/public-api' },
            { text: 'Analytics API v2', link: '/developer-docs/analytics-api' },
            { text: 'Webhooks', link: '/developer-docs/webhooks' },
            { text: 'API Keys', link: '/developer-docs/api-keys' },
            { text: 'SDK', link: '/developer-docs/sdk' },
            { text: 'MCP Server', link: '/developer-docs/mcp' },
            { text: 'OAuth Apps', link: '/developer-docs/oauth-apps' },
            { text: 'Plugs', link: '/developer-docs/plugs' },
            { text: 'Setup Gate', link: '/developer-docs/setup-gate' },
          ],
        },
        {
          text: 'AI & Providers',
          items: [
            { text: 'AI Architecture', link: '/developer-docs/ai-architecture' },
            { text: 'Agent Architecture', link: '/developer-docs/agent-architecture' },
            { text: 'Adding a Provider', link: '/developer-docs/adding-a-provider' },
            { text: 'Adding an AI Adapter', link: '/developer-docs/adding-an-ai-adapter' },
            { text: 'Adding a Media Studio', link: '/developer-docs/adding-a-media-studio' },
            { text: 'Provider Versions', link: '/developer-docs/provider-versions' },
          ],
        },
        {
          text: 'More',
          items: [
            { text: 'Designer', link: '/developer-docs/designer' },
            { text: 'Dashboard', link: '/developer-docs/dashboard' },
            { text: 'Local Development', link: '/developer-docs/local-development' },
            { text: 'Testing', link: '/developer-docs/testing' },
            { text: 'Contributing', link: '/developer-docs/contributing' },
            { text: 'Glossary', link: '/developer-docs/glossary' },
          ],
        },
      ],
      '/operations-guide/': [
        {
          text: 'Operations Guide',
          items: [
            { text: 'Introduction', link: '/operations-guide/' },
            { text: 'Requirements', link: '/operations-guide/requirements' },
            { text: 'Docker Deployment', link: '/operations-guide/docker' },
            { text: 'Configuration', link: '/operations-guide/configuration' },
            { text: 'Inngest & Cron', link: '/operations-guide/inngest-and-cron' },
            { text: 'Video Rendering', link: '/operations-guide/video-rendering' },
            { text: 'Storage Setup', link: '/operations-guide/storage' },
            { text: 'Backup & Retention', link: '/operations-guide/backup-and-retention' },
            { text: 'Scaling & Deployment', link: '/operations-guide/scaling' },
            { text: 'Upgrading', link: '/operations-guide/upgrading' },
            { text: 'Schema Rollback', link: '/operations-guide/schema-rollback' },
            { text: 'Security', link: '/operations-guide/security' },
            { text: 'OAuth / SSO', link: '/operations-guide/oauth-sso' },
            { text: 'Subscriptions & Stripe', link: '/operations-guide/subscriptions' },
          ],
        },
      ],
    },
  },
  rewrites: {
    '/getting-started/overview': '/user-guide/',
    '/getting-started/quickstart': '/user-guide/getting-started',
    '/features/calendar-and-posts': '/user-guide/calendar',
    '/features/analytics': '/user-guide/analytics',
    '/features/ai-features': '/user-guide/ai-tools',
    '/features/ai-generation': '/user-guide/ai-tools',
    '/features/social-comments': '/user-guide/social-comments',
    '/features/campaigns': '/user-guide/campaigns',
    '/features/bulk-scheduling': '/user-guide/bulk-import',
    '/features/watchlist': '/user-guide/watchlist',
    '/features/content-qa-preflight': '/user-guide/composer',
    '/features/provider-capabilities': '/user-guide/supported-channels',
    '/channels/overview': '/user-guide/getting-started',
    '/channels/setup-per-provider': '/user-guide/settings',
    '/channels/comments': '/user-guide/supported-channels',
    '/channels/tumblr-pixelfed-peertube': '/user-guide/',
    '/api/overview': '/developer-docs/',
    '/api/public-api': '/developer-docs/public-api',
    '/api/analytics-v2-api': '/developer-docs/analytics-api',
    '/api/mcp': '/developer-docs/mcp',
    '/api/automation': '/developer-docs/public-api',
    '/developers/architecture': '/developer-docs/architecture',
    '/developers/backend': '/developer-docs/backend-conventions',
    '/developers/frontend': '/developer-docs/frontend-conventions',
    '/developers/ai-architecture': '/developer-docs/ai-architecture',
    '/developers/adding-a-provider': '/developer-docs/adding-a-provider',
    '/developers/adding-an-ai-adapter': '/developer-docs/adding-an-ai-adapter',
    '/developers/database': '/developer-docs/database',
    '/developers/testing': '/developer-docs/testing',
    '/developers/contributing': '/developer-docs/contributing',
    '/developers/data-model': '/developer-docs/data-model',
    '/self-hosting/requirements': '/operations-guide/requirements',
    '/self-hosting/docker': '/operations-guide/docker',
    '/self-hosting/configuration': '/operations-guide/configuration',
    '/self-hosting/temporal-and-cron': '/operations-guide/inngest-and-cron',
    '/self-hosting/inngest-and-cron': '/operations-guide/inngest-and-cron',
    '/self-hosting/storage': '/operations-guide/storage',
    '/self-hosting/backup-and-retention': '/operations-guide/backup-and-retention',
    '/self-hosting/upgrading': '/operations-guide/upgrading',
    '/self-hosting/security': '/operations-guide/security',
    '/self-hosting/oauth-sso': '/operations-guide/oauth-sso',
    '/reference/env-vars': '/operations-guide/configuration',
    '/reference/data-model': '/developer-docs/data-model',
    '/reference/provider-capabilities': '/user-guide/supported-channels',
    '/reference/provider-versions': '/developer-docs/provider-versions',
    '/reference/glossary': '/developer-docs/glossary',
    '/reference/changes-from-upstream': '/',
    '/reference/CHANGES_FROM_UPSTREAM': '/',
    '/CHANGES_FROM_UPSTREAM': '/',
    '/features/media-library': '/user-guide/media-library',
    '/features/composer': '/user-guide/composer',
    '/features/settings': '/user-guide/settings',
    '/api/webhooks': '/developer-docs/webhooks',
    '/api/plugs': '/developer-docs/plugs',
    '/api/sdk': '/developer-docs/sdk',
    '/api/oauth-apps': '/developer-docs/oauth-apps',
    '/user-guide/billing': '/user-guide/subscription-and-billing',
    '/user-guide/media/replicate-studio': '/user-guide/media/replicate',
  },
})
