import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Postmill Docs',
  description: 'Schedule social & chat posts across 36 channels',
  themeConfig: {
    nav: [
      { text: 'User Guide', link: '/user-guide/' },
      { text: 'Developer Docs', link: '/developer-docs/' },
      { text: 'Operations Guide', link: '/operations-guide/' },
      { text: 'Reference', link: '/reference/' },
    ],
    sidebar: {
      '/user-guide/': [
        {
          text: 'User Guide',
          items: [
            { text: 'Introduction', link: '/user-guide/' },
            { text: 'Getting Started', link: '/user-guide/getting-started' },
            { text: 'Calendar', link: '/user-guide/calendar' },
            { text: 'Composer', link: '/user-guide/composer' },
            { text: 'Bulk Import', link: '/user-guide/bulk-import' },
            { text: 'Analytics', link: '/user-guide/analytics' },
            { text: 'Watchlist', link: '/user-guide/watchlist' },
            { text: 'Social Comments', link: '/user-guide/social-comments' },
            { text: 'Campaigns', link: '/user-guide/campaigns' },
            { text: 'Media Library', link: '/user-guide/media-library' },
            { text: 'AI Tools', link: '/user-guide/ai-tools' },
            { text: 'Settings', link: '/user-guide/settings' },
            { text: 'Billing', link: '/user-guide/billing' },
          ],
        },
      ],
      '/developer-docs/': [
        {
          text: 'Developer Docs',
          items: [
            { text: 'Introduction', link: '/developer-docs/' },
            { text: 'Architecture', link: '/developer-docs/architecture' },
            { text: 'Public API v1', link: '/developer-docs/public-api' },
            { text: 'Analytics API v2', link: '/developer-docs/analytics-api' },
            { text: 'MCP', link: '/developer-docs/mcp' },
            { text: 'OAuth Apps', link: '/developer-docs/oauth-apps' },
            { text: 'Plugs', link: '/developer-docs/plugs' },
            { text: 'SDK', link: '/developer-docs/sdk' },
            { text: 'Webhooks', link: '/developer-docs/webhooks' },
            { text: 'Adding a Provider', link: '/developer-docs/adding-a-provider' },
            { text: 'Adding an AI Adapter', link: '/developer-docs/adding-an-ai-adapter' },
            { text: 'AI Architecture', link: '/developer-docs/ai-architecture' },
            { text: 'Database', link: '/developer-docs/database' },
            { text: 'Data Model', link: '/developer-docs/data-model' },
            { text: 'Backend Conventions', link: '/developer-docs/backend-conventions' },
            { text: 'Frontend Conventions', link: '/developer-docs/frontend-conventions' },
            { text: 'Testing', link: '/developer-docs/testing' },
            { text: 'Contributing', link: '/developer-docs/contributing' },
          ],
        },
      ],
      '/operations-guide/': [
        {
          text: 'Operations Guide',
          items: [
            { text: 'Introduction', link: '/operations-guide/' },
            { text: 'Requirements', link: '/operations-guide/requirements' },
            { text: 'Docker Deployment', link: '/operations-guide/docker' },
            { text: 'Configuration', link: '/operations-guide/configuration' },
            { text: 'Inngest & Cron', link: '/operations-guide/inngest-and-cron' },
            { text: 'Storage Setup', link: '/operations-guide/storage' },
            { text: 'Backup & Retention', link: '/operations-guide/backup-and-retention' },
            { text: 'Upgrading', link: '/operations-guide/upgrading' },
            { text: 'Security', link: '/operations-guide/security' },
            { text: 'OAuth / SSO', link: '/operations-guide/oauth-sso' },
          ],
        },
      ],
      '/reference/': [
        {
          text: 'Reference',
          items: [
            { text: 'Overview', link: '/reference/' },
            { text: 'Changes From Upstream', link: '/reference/changes-from-upstream' },
            { text: 'Provider Capabilities', link: '/reference/provider-capabilities' },
            { text: 'Glossary', link: '/reference/glossary' },
          ],
        },
      ],
    },
  },
  rewrites: {
    '/getting-started/overview': '/user-guide/',
    '/getting-started/quickstart': '/user-guide/getting-started',
    '/features/calendar-and-posts': '/user-guide/calendar',
    '/features/analytics': '/user-guide/analytics',
    '/features/ai-features': '/user-guide/ai-tools',
    '/features/ai-generation': '/user-guide/ai-tools',
    '/features/social-comments': '/user-guide/social-comments',
    '/features/campaigns': '/user-guide/campaigns',
    '/features/bulk-scheduling': '/user-guide/bulk-import',
    '/features/watchlist': '/user-guide/watchlist',
    '/features/content-qa-preflight': '/user-guide/composer',
    '/features/provider-capabilities': '/reference/provider-capabilities',
    '/channels/overview': '/user-guide/getting-started',
    '/channels/setup-per-provider': '/user-guide/settings',
    '/channels/comments': '/reference/provider-capabilities',
    '/channels/tumblr-pixelfed-peertube': '/user-guide/',
    '/api/overview': '/developer-docs/',
    '/api/public-api': '/developer-docs/public-api',
    '/api/analytics-v2-api': '/developer-docs/analytics-api',
    '/api/mcp': '/developer-docs/mcp',
    '/api/automation': '/developer-docs/public-api',
    '/developers/architecture': '/developer-docs/architecture',
    '/developers/backend': '/developer-docs/backend-conventions',
    '/developers/frontend': '/developer-docs/frontend-conventions',
    '/developers/ai-architecture': '/developer-docs/ai-architecture',
    '/developers/adding-a-provider': '/developer-docs/adding-a-provider',
    '/developers/adding-an-ai-adapter': '/developer-docs/adding-an-ai-adapter',
    '/developers/database': '/developer-docs/database',
    '/developers/testing': '/developer-docs/testing',
    '/developers/contributing': '/developer-docs/contributing',
    '/self-hosting/requirements': '/operations-guide/requirements',
    '/self-hosting/docker': '/operations-guide/docker',
    '/self-hosting/configuration': '/operations-guide/configuration',
    '/self-hosting/temporal-and-cron': '/operations-guide/inngest-and-cron',
    '/self-hosting/inngest-and-cron': '/operations-guide/inngest-and-cron',
    '/self-hosting/storage': '/operations-guide/storage',
    '/self-hosting/backup-and-retention': '/operations-guide/backup-and-retention',
    '/self-hosting/upgrading': '/operations-guide/upgrading',
    '/reference/env-vars': '/operations-guide/configuration',
    '/reference/data-model': '/developer-docs/data-model',
    '/CHANGES_FROM_UPSTREAM': '/reference/changes-from-upstream',
    '/features/media-library': '/user-guide/media-library',
    '/features/composer': '/user-guide/composer',
    '/features/settings': '/user-guide/settings',
    '/api/webhooks': '/developer-docs/webhooks',
    '/api/plugs': '/developer-docs/plugs',
    '/api/sdk': '/developer-docs/sdk',
    '/api/oauth-apps': '/developer-docs/oauth-apps',
    '/developers/data-model': '/developer-docs/data-model',
    '/self-hosting/security': '/operations-guide/security',
    '/self-hosting/oauth-sso': '/operations-guide/oauth-sso',
    '/reference/CHANGES_FROM_UPSTREAM': '/reference/changes-from-upstream',
  },
})
