import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen } from '@testing-library/react';

vi.mock('@gitroom/react/translation/get.transation.service.client', () => ({
  useT:
    () =>
    (_k: string, d: string, vars?: Record<string, unknown>) =>
      vars ? d.replace(/\{\{(\w+)\}\}/g, (_m, k) => String(vars[k])) : d,
}));

vi.mock('@gitroom/frontend/components/layout/use-ai-active', () => ({
  AI_SETUP_HREF: '/settings/ai/llm-providers',
}));

const mockNarrate = vi.fn();
vi.mock('../hooks/useNarrate', () => {
  class NarrateError extends Error {
    code: number;
    constructor(message: string, code: number) {
      super(message);
      this.code = code;
    }
  }
  return {
    useNarrate: () => mockNarrate,
    NarrateError,
  };
});

import { NarrateModal } from './narrate.modal';
import { NarrateError } from '../hooks/useNarrate';

describe('NarrateModal', () => {
  beforeEach(() => vi.clearAllMocks());

  it('always renders the "Generated by AI" badge', () => {
    mockNarrate.mockReturnValue(new Promise(() => {}));
    render(<NarrateModal from="2024-01-01" to="2024-01-31" />);
    expect(screen.getByText(/Generated by AI/i)).toBeTruthy();
  });

  it('renders the pulsing loading skeleton while narration is in flight', () => {
    mockNarrate.mockReturnValue(new Promise(() => {}));
    const { container } = render(<NarrateModal from="a" to="b" />);
    expect(container.querySelector('.animate-pulse')).toBeTruthy();
    // narrate is invoked on mount with the range
    expect(mockNarrate).toHaveBeenCalledWith('a', 'b');
  });

  it('renders the narration text on success', async () => {
    mockNarrate.mockResolvedValue('It was a strong week for reach.');
    render(<NarrateModal from="a" to="b" />);
    expect(await screen.findByText('It was a strong week for reach.')).toBeTruthy();
  });

  it('renders the empty state when the narration text is blank', async () => {
    mockNarrate.mockResolvedValue('');
    const { container } = render(<NarrateModal from="a" to="b" />);
    expect(await screen.findByText(/No summary available for this period/i)).toBeTruthy();
    // loading skeleton is gone
    expect(container.querySelector('.animate-pulse')).toBeFalsy();
  });

  it('renders the AI-off (503) message with a link to Settings → AI', async () => {
    mockNarrate.mockRejectedValue(new NarrateError('nope', 503));
    render(<NarrateModal from="a" to="b" />);
    expect(await screen.findByText(/AI is not configured for this workspace/i)).toBeTruthy();
    const link = screen.getByText(/Go to Settings → AI/i).closest('a') as HTMLAnchorElement;
    expect(link.getAttribute('href')).toBe('/settings/ai/llm-providers');
  });

  it('renders the budget-exceeded (429) message', async () => {
    mockNarrate.mockRejectedValue(new NarrateError('budget', 429));
    render(<NarrateModal from="a" to="b" />);
    expect(await screen.findByText(/Your AI budget for this period has been reached/i)).toBeTruthy();
  });

  it('renders the generic failure message for other NarrateError codes', async () => {
    mockNarrate.mockRejectedValue(new NarrateError('boom', 500));
    render(<NarrateModal from="a" to="b" />);
    expect(await screen.findByText(/Could not generate a summary right now/i)).toBeTruthy();
  });

  it('renders the generic failure message for a non-NarrateError rejection (code -1)', async () => {
    mockNarrate.mockRejectedValue(new Error('network'));
    render(<NarrateModal from="a" to="b" />);
    expect(await screen.findByText(/Could not generate a summary right now/i)).toBeTruthy();
  });

  it('re-runs narration when the range changes', async () => {
    mockNarrate.mockResolvedValue('first');
    const { rerender } = render(<NarrateModal from="a" to="b" />);
    expect(await screen.findByText('first')).toBeTruthy();
    mockNarrate.mockResolvedValue('second');
    rerender(<NarrateModal from="c" to="d" />);
    expect(await screen.findByText('second')).toBeTruthy();
    expect(mockNarrate).toHaveBeenLastCalledWith('c', 'd');
  });
});
