'use client';

import { FC, useEffect, useState } from 'react';
import Link from 'next/link';
import { useT } from '@gitroom/react/translation/get.transation.service.client';
import { useNarrate, NarrateError } from '../hooks/useNarrate';
import { AI_SETUP_HREF } from '@gitroom/frontend/components/layout/use-ai-active';

// Actual narration UI. A fresh instance is mounted (via key on the public
// wrapper) whenever the requested period changes, so initial state is enough
// and the effect does not need any synchronous setState calls.
const NarrateModalInner: FC<{ from: string; to: string }> = ({ from, to }) => {
  const t = useT();
  const narrate = useNarrate();
  const [text, setText] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [errorCode, setErrorCode] = useState<number | null>(null);

  useEffect(() => {
    let active = true;
    narrate(from, to)
      .then((result) => {
        if (active) setText(result);
      })
      .catch((e: unknown) => {
        if (!active) return;
        setErrorCode(e instanceof NarrateError ? e.code : -1);
      })
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => {
      active = false;
    };
  }, [narrate, from, to]);

  return (
    <div className="w-full sm:w-[520px] max-w-full flex flex-col gap-[16px]">
      <div className="flex items-center gap-[8px]">
        <span className="inline-flex items-center gap-[6px] text-[11px] font-medium text-newTableText uppercase tracking-wide px-[8px] py-[3px] rounded-full bg-newTableHeader border border-newTableBorder">
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1" strokeLinecap="round" />
          </svg>
          {t('analytics_generated_by_ai', 'Generated by AI')}
        </span>
      </div>

      {loading && (
        <div className="animate-pulse space-y-[8px]">
          <div className="h-[14px] bg-newTableHeader rounded-[4px] w-full" />
          <div className="h-[14px] bg-newTableHeader rounded-[4px] w-[92%]" />
          <div className="h-[14px] bg-newTableHeader rounded-[4px] w-[80%]" />
          <div className="h-[14px] bg-newTableHeader rounded-[4px] w-[88%]" />
        </div>
      )}

      {!loading && errorCode === 503 && (
        <div className="text-[13px] text-newTableText">
          {t(
            'analytics_narrate_ai_off',
            'AI is not configured for this workspace. Set up a provider in Settings → AI to enable narration.'
          )}
          <div className="mt-[12px]">
            <Link
              href={AI_SETUP_HREF}
              className="inline-flex px-[14px] py-[6px] text-[13px] font-medium bg-btnPrimary text-white rounded-[8px] hover:opacity-90 transition-opacity"
            >
              {t('analytics_narrate_go_settings', 'Go to Settings → AI')}
            </Link>
          </div>
        </div>
      )}

      {!loading && errorCode === 429 && (
        <div className="text-[13px] text-amber-600">
          {t(
            'analytics_narrate_budget',
            'Your AI budget for this period has been reached. Try again later or adjust your budget in Settings → AI.'
          )}
        </div>
      )}

      {!loading && errorCode != null && errorCode !== 503 && errorCode !== 429 && (
        <div className="text-[13px] text-amber-600">
          {t('analytics_narrate_failed', 'Could not generate a summary right now. Please try again.')}
        </div>
      )}

      {!loading && errorCode == null && text && (
        <p className="text-[14px] leading-[22px] text-textColor whitespace-pre-wrap">
          {text}
        </p>
      )}

      {!loading && errorCode == null && !text && (
        <p className="text-[13px] text-newTableText">
          {t('analytics_narrate_empty', 'No summary available for this period.')}
        </p>
      )}
    </div>
  );
};

// "Explain this period" narration modal (7.5). Fetches on mount; renders the
// text with a "generated by AI" label. AI-off (503) shows the standard
// "not configured → Settings → AI" message; budget-exceeded (429) is explicit.
export const NarrateModal: FC<{ from: string; to: string }> = ({ from, to }) => {
  return <NarrateModalInner key={`${from}|${to}`} from={from} to={to} />;
};
