export * from './identity';
export * from './manifest';
export * from './verification';
export * from './module';
export * from './ports';
export * from './errors';
export { ProviderKernel } from './kernel';
export * from './testing/conformance';

export * from './domains/ai';
export * from './domains/ai-helpers';
export * from './domains/languages';
export * from './domains/media';
export * from './domains/media-helpers';
export * from './domains/metadata';
export * from './domains/storage';
export * from './domains/storage-helpers';
export * from './domains/shortlink';
export * from './domains/social';
export * from './domains/social-base';
export * from './domains/social-provider';
export * from './domains/social-capabilities';
export * from './domains/social-make-id';
export * from './domains/social-tool-decorator';
export * from './domains/social-rules-decorator';
export * from './domains/social-credentials';
export * from './domains/social-dtos';
export * from './domains/social-bridge';
export * from './domains/social-families';
export * from './domains/vpn';
export * from './domains/contentpack';
export * from './domains/email';
export * from './domains/auth';

export * as AiDomain from './domains/ai';
export * as MediaDomain from './domains/media';
export * as StorageDomain from './domains/storage';
export * as ShortlinkDomain from './domains/shortlink';
export * as SocialDomain from './domains/social';
export * as VpnDomain from './domains/vpn';
export * as ContentPackDomain from './domains/contentpack';
export * as EmailDomain from './domains/email';
export * as AuthDomain from './domains/auth';
