// AUTO-GENERATED by scratchpad/gen-routes.mjs from apps/frontend/src/app page.tsx files.
// Dynamic segments substituted with seeded local IDs. Regenerate after adding routes.
export interface RouteDef {
  name: string;
  path: string;
  area: string;
  /** Public/auth route — crawl WITHOUT a session; do not flag REDIRECTED_TO_AUTH. */
  publicRoute?: boolean;
  expectsContent?: boolean;
  minActionables?: number;
  /** Element visibility is RBAC/tier gated — a member/free persona may see fewer/no actionables. */
  memberGated?: boolean;
}

/** Backend origin the frontend calls directly (cross-origin) — used by the auditor. */
export const BACKEND_ORIGIN = process.env.E2E_BACKEND_ORIGIN || 'http://localhost:3000';
/** Frontend base — overridden by Playwright baseURL; kept for URL display stripping. */
export const BASE = process.env.E2E_BASE || 'http://localhost:4200';

export const ROUTES: RouteDef[] = [
  {
    "name": "Home",
    "path": "/",
    "area": "dashboard",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 3,
    "memberGated": false
  },
  {
    "name": "agents",
    "path": "/agents",
    "area": "agents",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "analytics",
    "path": "/analytics",
    "area": "analytics",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "analytics › v2",
    "path": "/analytics/v2",
    "area": "analytics",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "auth",
    "path": "/auth",
    "area": "auth",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "auth › activate",
    "path": "/auth/activate",
    "area": "auth",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "auth › activate › SEED-CODE",
    "path": "/auth/activate/SEED-CODE",
    "area": "auth",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "auth › forgot",
    "path": "/auth/forgot",
    "area": "auth",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "auth › forgot › SEED-TOKEN",
    "path": "/auth/forgot/SEED-TOKEN",
    "area": "auth",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "auth › login",
    "path": "/auth/login",
    "area": "auth",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "auth › login-required",
    "path": "/auth/login-required",
    "area": "auth",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "billing",
    "path": "/billing",
    "area": "billing",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "billing › lifetime",
    "path": "/billing/lifetime",
    "area": "billing",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "campaigns",
    "path": "/campaigns",
    "area": "campaigns",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "campaigns › df019cb8-83ca-48b9-9b01-7fec761f2274",
    "path": "/campaigns/df019cb8-83ca-48b9-9b01-7fec761f2274",
    "area": "campaigns",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "campaigns › df019cb8-83ca-48b9-9b01-7fec761f2274 › report",
    "path": "/campaigns/df019cb8-83ca-48b9-9b01-7fec761f2274/report",
    "area": "campaigns",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "comments",
    "path": "/comments",
    "area": "comments",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "dashboard",
    "path": "/dashboard",
    "area": "dashboard",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 3,
    "memberGated": false
  },
  {
    "name": "err",
    "path": "/err",
    "area": "misc",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "files",
    "path": "/files",
    "area": "files",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "integrations › social › x",
    "path": "/integrations/social/x",
    "area": "onboarding",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "media",
    "path": "/media",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › ai-designer",
    "path": "/media/ai-designer",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › azure",
    "path": "/media/azure",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › bedrock",
    "path": "/media/bedrock",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › black-forest-labs",
    "path": "/media/black-forest-labs",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › deepgram",
    "path": "/media/deepgram",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › deepinfra",
    "path": "/media/deepinfra",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › designer",
    "path": "/media/designer",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › did",
    "path": "/media/did",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › elevenlabs",
    "path": "/media/elevenlabs",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › fireworks",
    "path": "/media/fireworks",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › gateway",
    "path": "/media/gateway",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › genviral",
    "path": "/media/genviral",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › google-ai",
    "path": "/media/google-ai",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › groq",
    "path": "/media/groq",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › hedra",
    "path": "/media/hedra",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › heygen",
    "path": "/media/heygen",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › higgsfield",
    "path": "/media/higgsfield",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › ideogram",
    "path": "/media/ideogram",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › kling",
    "path": "/media/kling",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › leonardo",
    "path": "/media/leonardo",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › ltx",
    "path": "/media/ltx",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › luma",
    "path": "/media/luma",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › minimax",
    "path": "/media/minimax",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › openai",
    "path": "/media/openai",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › openrouter",
    "path": "/media/openrouter",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › pika",
    "path": "/media/pika",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › qwen",
    "path": "/media/qwen",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › recraft",
    "path": "/media/recraft",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › reelfarm",
    "path": "/media/reelfarm",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › replicate",
    "path": "/media/replicate",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › runway",
    "path": "/media/runway",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › siliconflow",
    "path": "/media/siliconflow",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › sora",
    "path": "/media/sora",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › stability-ai",
    "path": "/media/stability-ai",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › stock-audio",
    "path": "/media/stock-audio",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › stock-icons",
    "path": "/media/stock-icons",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › stock-photos",
    "path": "/media/stock-photos",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › stock-stickers",
    "path": "/media/stock-stickers",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › stock-vectors",
    "path": "/media/stock-vectors",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › stock-videos",
    "path": "/media/stock-videos",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › suno",
    "path": "/media/suno",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › tavus",
    "path": "/media/tavus",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › togetherai",
    "path": "/media/togetherai",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › vertex",
    "path": "/media/vertex",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › wan",
    "path": "/media/wan",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "media › xai",
    "path": "/media/xai",
    "area": "media",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": true
  },
  {
    "name": "oauth › authorize",
    "path": "/oauth/authorize",
    "area": "onboarding",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "p › cmrcwb4va001rp3bx41l3bdv1",
    "path": "/p/cmrcwb4va001rp3bx41l3bdv1",
    "area": "misc",
    "publicRoute": true,
    "expectsContent": false,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "posts",
    "path": "/posts",
    "area": "posts",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "posts › post",
    "path": "/posts/post",
    "area": "posts",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "profile › 34fd9f06-f556-4b64-94d9-cb311eebb8ff",
    "path": "/profile/34fd9f06-f556-4b64-94d9-cb311eebb8ff",
    "area": "profile",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "provider › add",
    "path": "/provider/add",
    "area": "provider",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false,
    "note": "param→add"
  },
  {
    "name": "provider › add",
    "path": "/provider/add",
    "area": "provider",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "replies",
    "path": "/replies",
    "area": "comments",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "settings",
    "path": "/settings",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai",
    "path": "/settings/ai",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › brands",
    "path": "/settings/ai/brands",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › brands › cmrcwb57d001vp3bxv8rqqm0y",
    "path": "/settings/ai/brands/cmrcwb57d001vp3bxv8rqqm0y",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › brands › cmrcwb57d001vp3bxv8rqqm0y › kit",
    "path": "/settings/ai/brands/cmrcwb57d001vp3bxv8rqqm0y/kit",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › brands › cmrcwb57d001vp3bxv8rqqm0y › knowledge",
    "path": "/settings/ai/brands/cmrcwb57d001vp3bxv8rqqm0y/knowledge",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › brands › cmrcwb57d001vp3bxv8rqqm0y › voice",
    "path": "/settings/ai/brands/cmrcwb57d001vp3bxv8rqqm0y/voice",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › llm-providers",
    "path": "/settings/ai/llm-providers",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › model-defaults",
    "path": "/settings/ai/model-defaults",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › prompt-library",
    "path": "/settings/ai/prompt-library",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › ai › prompt-templates",
    "path": "/settings/ai/prompt-templates",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › approved-apps",
    "path": "/settings/approved-apps",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › autopost",
    "path": "/settings/autopost",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › broadcast",
    "path": "/settings/broadcast",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › channels",
    "path": "/settings/channels",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › content",
    "path": "/settings/content",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › content › ai-media",
    "path": "/settings/content/ai-media",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › content › content-packs",
    "path": "/settings/content/content-packs",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › content › media-defaults",
    "path": "/settings/content/media-defaults",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › content › sets",
    "path": "/settings/content/sets",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › content › signatures",
    "path": "/settings/content/signatures",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › developers",
    "path": "/settings/developers",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › shortlinks",
    "path": "/settings/shortlinks",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › storage",
    "path": "/settings/storage",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › storage › audit",
    "path": "/settings/storage/audit",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › storage › providers",
    "path": "/settings/storage/providers",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › storage › usage",
    "path": "/settings/storage/usage",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › team",
    "path": "/settings/team",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › vpn",
    "path": "/settings/vpn",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "settings › webhooks",
    "path": "/settings/webhooks",
    "area": "settings",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 2,
    "memberGated": true
  },
  {
    "name": "setup",
    "path": "/setup",
    "area": "onboarding",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "share › campaign › 547a131358944a5fab789842fc8892f309bd97aa53bb62008f21867bbfc577a0",
    "path": "/share/campaign/547a131358944a5fab789842fc8892f309bd97aa53bb62008f21867bbfc577a0",
    "area": "share",
    "publicRoute": true,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  },
  {
    "name": "user › me",
    "path": "/user/me",
    "area": "profile",
    "publicRoute": false,
    "expectsContent": true,
    "minActionables": 1,
    "memberGated": false
  }
];

export const AREAS = ["dashboard","agents","analytics","auth","billing","campaigns","comments","misc","files","onboarding","media","posts","profile","provider","settings","share"];
