// Auto-generated by scripts/generate-studio-descriptor-registry.mjs.
// Do not edit by hand. Source of truth: apps/frontend/src/components/media-tools/*/descriptor.ts

export interface StudioFieldSchema {
  name: string;
  type: string;
}

export interface StudioTabSchema {
  key: string;
  operation: 'video' | 'image' | 'audio';
  model?: string;
  fields: StudioFieldSchema[];
}

export interface StudioDescriptorSchema {
  provider: string;
  tabs: StudioTabSchema[];
}

export const STUDIO_DESCRIPTOR_REGISTRY: Record<string, StudioDescriptorSchema> = {
  "azure": {
    "provider": "azure",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "n",
            "type": "number"
          }
        ]
      }
    ]
  },
  "bedrock": {
    "provider": "bedrock",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "n",
            "type": "number"
          }
        ]
      }
    ]
  },
  "black-forest-labs": {
    "provider": "black-forest-labs",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "width",
            "type": "number"
          },
          {
            "name": "height",
            "type": "number"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "output_format",
            "type": "select"
          },
          {
            "name": "prompt_upsampling",
            "type": "toggle"
          },
          {
            "name": "safety_tolerance",
            "type": "number"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      }
    ]
  },
  "deepinfra": {
    "provider": "deepinfra",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "width",
            "type": "number"
          },
          {
            "name": "height",
            "type": "number"
          },
          {
            "name": "num_inference_steps",
            "type": "number"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          }
        ]
      },
      {
        "key": "text-to-speech",
        "operation": "audio",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "preset_voice",
            "type": "text"
          }
        ]
      }
    ]
  },
  "did": {
    "provider": "did",
    "tabs": [
      {
        "key": "talking-avatar",
        "operation": "video",
        "fields": [
          {
            "name": "source_image",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "voice_provider",
            "type": "select"
          },
          {
            "name": "voice_id",
            "type": "text"
          },
          {
            "name": "stitch",
            "type": "toggle"
          }
        ]
      }
    ]
  },
  "elevenlabs": {
    "provider": "elevenlabs",
    "tabs": [
      {
        "key": "text-to-speech",
        "operation": "audio",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "voice_id",
            "type": "select"
          },
          {
            "name": "stability",
            "type": "number"
          },
          {
            "name": "similarity_boost",
            "type": "number"
          },
          {
            "name": "style",
            "type": "number"
          },
          {
            "name": "use_speaker_boost",
            "type": "toggle"
          }
        ]
      }
    ]
  },
  "fireworks": {
    "provider": "fireworks",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "num_inference_steps",
            "type": "number"
          },
          {
            "name": "guidance_scale",
            "type": "number"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      }
    ]
  },
  "gateway": {
    "provider": "gateway",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "n",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "seconds",
            "type": "number"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "image",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "seconds",
            "type": "number"
          }
        ]
      }
    ]
  },
  "genviral": {
    "provider": "genviral",
    "tabs": [
      {
        "key": "video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "image_url",
            "type": "media"
          },
          {
            "name": "audio_url",
            "type": "media"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "duration_seconds",
            "type": "number"
          },
          {
            "name": "fps",
            "type": "number"
          },
          {
            "name": "generate_audio",
            "type": "toggle"
          }
        ]
      }
    ]
  },
  "google": {
    "provider": "google",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "aspectRatio",
            "type": "select"
          },
          {
            "name": "sampleCount",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negativePrompt",
            "type": "text"
          },
          {
            "name": "aspectRatio",
            "type": "select"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "durationSeconds",
            "type": "number"
          }
        ]
      }
    ]
  },
  "groq": {
    "provider": "groq",
    "tabs": [
      {
        "key": "text-to-speech",
        "operation": "audio",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "voice",
            "type": "text"
          },
          {
            "name": "response_format",
            "type": "select"
          }
        ]
      }
    ]
  },
  "hedra": {
    "provider": "hedra",
    "tabs": [
      {
        "key": "character-video",
        "operation": "video",
        "fields": [
          {
            "name": "start_keyframe",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          }
        ]
      }
    ]
  },
  "higgsfield": {
    "provider": "higgsfield",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "model": "soul",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "width_and_height",
            "type": "select"
          },
          {
            "name": "quality",
            "type": "select"
          },
          {
            "name": "batch_size",
            "type": "number"
          },
          {
            "name": "image_url",
            "type": "media"
          },
          {
            "name": "enhance_prompt",
            "type": "toggle"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "image_url",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "enhance_prompt",
            "type": "toggle"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "speak",
        "operation": "video",
        "model": "speak",
        "fields": [
          {
            "name": "image_url",
            "type": "media"
          },
          {
            "name": "audio_url",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "quality",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "number"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      }
    ]
  },
  "ideogram": {
    "provider": "ideogram",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "rendering_speed",
            "type": "select"
          },
          {
            "name": "style_type",
            "type": "select"
          },
          {
            "name": "magic_prompt",
            "type": "select"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "num_images",
            "type": "number"
          }
        ]
      }
    ]
  },
  "fal": {
    "provider": "fal",
    "tabs": [
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "duration",
            "type": "select"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "cfg_scale",
            "type": "number"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "image_url",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "duration",
            "type": "select"
          },
          {
            "name": "cfg_scale",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "model": "fal-ai/pika/v2.2/text-to-video",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "select"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "model": "fal-ai/pika/v2.2/image-to-video",
        "fields": [
          {
            "name": "image_url",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "select"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "pikaffects",
        "operation": "video",
        "model": "fal-ai/pika/v1.5/pikaffects",
        "fields": [
          {
            "name": "image_url",
            "type": "media"
          },
          {
            "name": "pikaffect",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      }
    ]
  },
  "leonardo": {
    "provider": "leonardo",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "width",
            "type": "number"
          },
          {
            "name": "height",
            "type": "number"
          },
          {
            "name": "num_images",
            "type": "number"
          }
        ]
      }
    ]
  },
  "ltx": {
    "provider": "ltx",
    "tabs": [
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "number"
          },
          {
            "name": "fps",
            "type": "number"
          },
          {
            "name": "camera_motion",
            "type": "select"
          },
          {
            "name": "generate_audio",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "image_uri",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "number"
          },
          {
            "name": "fps",
            "type": "number"
          },
          {
            "name": "camera_motion",
            "type": "select"
          },
          {
            "name": "last_frame_uri",
            "type": "media"
          },
          {
            "name": "generate_audio",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "audio-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "audio_uri",
            "type": "media"
          },
          {
            "name": "image_uri",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "number"
          }
        ]
      }
    ]
  },
  "luma": {
    "provider": "luma",
    "tabs": [
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "select"
          },
          {
            "name": "loop",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "start_image_url",
            "type": "media"
          },
          {
            "name": "end_image_url",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "select"
          },
          {
            "name": "loop",
            "type": "toggle"
          }
        ]
      }
    ]
  },
  "minimax": {
    "provider": "minimax",
    "tabs": [
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "prompt_optimizer",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "first_frame_image",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "prompt_optimizer",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "subject-reference",
        "operation": "video",
        "model": "S2V-01",
        "fields": [
          {
            "name": "subject_image",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "prompt_optimizer",
            "type": "toggle"
          }
        ]
      }
    ]
  },
  "openai": {
    "provider": "openai",
    "tabs": [
      {
        "key": "gpt-image",
        "operation": "image",
        "model": "gpt-image-1",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "quality",
            "type": "select"
          },
          {
            "name": "background",
            "type": "select"
          },
          {
            "name": "output_format",
            "type": "select"
          },
          {
            "name": "n",
            "type": "number"
          }
        ]
      },
      {
        "key": "dalle-3",
        "operation": "image",
        "model": "dall-e-3",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "quality",
            "type": "select"
          },
          {
            "name": "style",
            "type": "select"
          }
        ]
      },
      {
        "key": "text-to-speech",
        "operation": "audio",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "voice",
            "type": "select"
          },
          {
            "name": "response_format",
            "type": "select"
          },
          {
            "name": "speed",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "seconds",
            "type": "select"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "input_reference",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "seconds",
            "type": "select"
          }
        ]
      }
    ]
  },
  "openrouter": {
    "provider": "openrouter",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "n",
            "type": "number"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "output_format",
            "type": "select"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      }
    ]
  },
  "qwen": {
    "provider": "qwen",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "prompt_extend",
            "type": "toggle"
          },
          {
            "name": "watermark",
            "type": "toggle"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "number"
          },
          {
            "name": "prompt_extend",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "img_url",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "prompt_extend",
            "type": "toggle"
          }
        ]
      }
    ]
  },
  "recraft": {
    "provider": "recraft",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "style",
            "type": "select"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "n",
            "type": "number"
          }
        ]
      }
    ]
  },
  "reelfarm": {
    "provider": "reelfarm",
    "tabs": [
      {
        "key": "slideshow",
        "operation": "video",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "image_1",
            "type": "media"
          },
          {
            "name": "image_2",
            "type": "media"
          },
          {
            "name": "image_3",
            "type": "media"
          },
          {
            "name": "image_4",
            "type": "media"
          }
        ]
      }
    ]
  },
  "runway": {
    "provider": "runway",
    "tabs": [
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "promptImage",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "duration",
            "type": "select"
          },
          {
            "name": "ratio",
            "type": "select"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-image",
        "operation": "image",
        "model": "gen4_image",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "ratio",
            "type": "select"
          }
        ]
      }
    ]
  },
  "siliconflow": {
    "provider": "siliconflow",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "image_size",
            "type": "select"
          },
          {
            "name": "num_inference_steps",
            "type": "number"
          },
          {
            "name": "batch_size",
            "type": "number"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "image_size",
            "type": "select"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "image",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "image_size",
            "type": "select"
          }
        ]
      },
      {
        "key": "text-to-speech",
        "operation": "audio",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "voice",
            "type": "text"
          },
          {
            "name": "response_format",
            "type": "select"
          }
        ]
      }
    ]
  },
  "stability-ai": {
    "provider": "stability-ai",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "aspect_ratio",
            "type": "select"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "style_preset",
            "type": "select"
          },
          {
            "name": "output_format",
            "type": "select"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      }
    ]
  },
  "suno": {
    "provider": "suno",
    "tabs": [
      {
        "key": "song",
        "operation": "audio",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "style",
            "type": "text"
          },
          {
            "name": "title",
            "type": "text"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "vocalGender",
            "type": "select"
          },
          {
            "name": "styleWeight",
            "type": "number"
          },
          {
            "name": "instrumental",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "instrumental",
        "operation": "audio",
        "fields": [
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "style",
            "type": "text"
          },
          {
            "name": "title",
            "type": "text"
          },
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "styleWeight",
            "type": "number"
          },
          {
            "name": "instrumental",
            "type": "toggle"
          }
        ]
      }
    ]
  },
  "tavus": {
    "provider": "tavus",
    "tabs": [
      {
        "key": "replica-video",
        "operation": "video",
        "fields": [
          {
            "name": "replica_id",
            "type": "text"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "video_name",
            "type": "text"
          }
        ]
      }
    ]
  },
  "togetherai": {
    "provider": "togetherai",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "width",
            "type": "number"
          },
          {
            "name": "height",
            "type": "number"
          },
          {
            "name": "steps",
            "type": "number"
          },
          {
            "name": "n",
            "type": "number"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "ratio",
            "type": "select"
          },
          {
            "name": "seconds",
            "type": "number"
          },
          {
            "name": "generate_audio",
            "type": "toggle"
          },
          {
            "name": "seed",
            "type": "number"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "frame_image",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "ratio",
            "type": "select"
          },
          {
            "name": "seconds",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-speech",
        "operation": "audio",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "voice",
            "type": "text"
          },
          {
            "name": "response_format",
            "type": "select"
          }
        ]
      }
    ]
  },
  "vertex": {
    "provider": "vertex",
    "tabs": [
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negativePrompt",
            "type": "text"
          },
          {
            "name": "aspectRatio",
            "type": "select"
          },
          {
            "name": "durationSeconds",
            "type": "number"
          }
        ]
      },
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negativePrompt",
            "type": "text"
          },
          {
            "name": "aspectRatio",
            "type": "select"
          },
          {
            "name": "sampleCount",
            "type": "number"
          }
        ]
      }
    ]
  },
  "wan": {
    "provider": "wan",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "n",
            "type": "number"
          },
          {
            "name": "prompt_extend",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "text-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "size",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "number"
          },
          {
            "name": "prompt_extend",
            "type": "toggle"
          }
        ]
      },
      {
        "key": "image-to-video",
        "operation": "video",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "img_url",
            "type": "media"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "negative_prompt",
            "type": "text"
          },
          {
            "name": "resolution",
            "type": "select"
          },
          {
            "name": "duration",
            "type": "number"
          }
        ]
      }
    ]
  },
  "xai": {
    "provider": "xai",
    "tabs": [
      {
        "key": "text-to-image",
        "operation": "image",
        "fields": [
          {
            "name": "model",
            "type": "select"
          },
          {
            "name": "prompt",
            "type": "prompt"
          },
          {
            "name": "n",
            "type": "number"
          }
        ]
      }
    ]
  }
};
